# Generated by Django 6.1 on 2026-08-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='is_anomaly',
            field=models.BooleanField(default=False),
        ),
    ]
